name: "Run"

on:
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
    - cron: "0 * * * *"
  # pull_request:
  # push:
  #   branches:
  #     - main
  #     - "releases/*"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm i
      - uses: ./
        with:
          githubToken: ${{ secrets.GITHUBTOKEN }}
          actor: ${{ github.actor }}